### ISSUE TITLE
interrogations sur la partie notion

### ISSUE THREAD

**Issue by Stat-FMr** [InseeFrLab/manuel-protection-tableaux#30]
pas au clair sur tableau large et long.
Pour moi, un tableau long est une représentation comme cela
DIM1 DIM2 INDICATEUR VAL
A1        B1     NB_ENT        12
A1        B1     CA               15 M€
(c'est la représentation dans le format SDMX)
Un tableau large va reprendre les indicateurs en ligne pour un même croisement
DIM1 DIM2    NB_ENT    CA
A1        B1        12           15 M€

autre interrogation sur cellule sensible : pour moi, c'est une variable qui est sensible (plus exactement une modalité d'une variable) et pas forcément une cellule. De plus, je ne comprends pas la phrase "Selon le type de données les cellules considérées comme sensibles varient. "

Pour le dernier paragraphe
La pose du secret (voir parties 2 à 4) nécessite de bien identifier les tableaux liés entre eux et les hiérarchies (emboîtées ou non). En fonction des liens identifiés, l'ensemble des tableaux à diffuser sera soit scindé (absence de relations) ou au contraire considéré d'un seul tenant (équations entre variables). Cette phase d'analyse de la demande, développée au Chapitre [3](https://inseefrlab.github.io/manuel-protection-tableaux/03_analyser_une_demande.html) va permettre de construire les tableaux à protéger, lesquels sont le plus souvent distincts des tableaux qui seront effectivement diffusés.

**Comment by clara-baudry** [comment]
J'ai remplacé par "Selon le type de données les règles peuvent varier ainsi les cellules considérées comme
sensibles varient elles aussi"

**Comment by clara-baudry** [comment]
autre interrogation sur cellule sensible : j'ai ajouté "sensible (ou confidentielle)"

**Comment by clara-baudry** [comment]
Ancienne version dernier paragraphe : 
Les tableaux qui seront finalement diffusés ne sont pas les mêmes que
les tableaux à protéger. En effet, les tableaux à protéger sont le
résultat de l'analyse de la demande. Cette analyse consiste à identifier
les tableaux liés entre eux et les hiérarchies (emboîtées ou non). Dès
lors, l'identification de ces liens va nous pousser à regrouper
différents tableaux ou au contraire les séparer. Une fois l'analyse
terminée on se retrouve avec les tableaux à protéger, le secret sera
appliqué sur ces tableaux et c'est seulement une fois la procédure
terminée que l'on pourra reporter le secret identifié sur les tableaux à
protéger sur les tableaux à diffuser. Cette phase d'analyse est
développée au Chapitre [-@sec-analyserdemande].
